### ISSUE TITLE
코딩스타일 정하기

### ISSUE THREAD

**Issue by cmygray** [Esdyee/Nanum-Project#31]
1. import 코드 작성 규칙 (들여쓰기, 줄바꿈, ng모듈, npm, 컴포넌트 구분하기 위한 행 간격 등등...)
1. indentation 
1. inline template 사용여부?

**Comment by cmygray** [comment]
1. import 코드 관련

- https://angular.io/guide/styleguide#style-03-06
- angular module / third-pary module / app-imports 각각 공백 한줄로 구분

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { APP_BASE_HREF, LocationStrategy, HashLocationStrategy } from '@angular/common/';

import { MaterialModule } from './module/material.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { QuillModule } from 'ngx-quill';

import { AppComponent } from './app.component';
import { LoginComponent } from './login/login.component';
import { TopicComponent } from './topic/topic.component';
```

**Comment by cmygray** [comment]
tslint.json을 건드리지 않고 정할 수 있는 규칙위주로 간단하게 모아보아요...

**Comment by Esdyee** [comment]
개인적으로 이번에 하면서 느낀 것은
저희같은 소규모 프로젝트에서는 import를 모듈별로 나누기보다도

Component, Service, Pipe, Module 끼리 모아서 정리하는게 개인적으로 편할 것 같다고 생각합니다.

indentation은 솔직히 가독성 측면에서는 4space = 1tab으로 해서 1tab 방식으로 쓰는게 좋은 것 같습니다.

**Comment by cmygray** [comment]
브랜치 네이밍 규칙 (`<label-name>`: `<branchname>`)

* new feature: `feature/<description>`
* fix plz: `hotfix/<description>`
* refactoring: `refactor/<description>`
