### ISSUE TITLE
@hotfix/filter-by-topic 사이드메뉴의 관심/전문분야 토픽 리스트 수정

### ISSUE THREAD

**Issue by cmygray** [Esdyee/Nanum-Project#52]
서버 API 변경으로 인한 것 같은데, 아직 수정 안하셨다면 제가 메인피드 작업하면서 손대도 괜찮을까요?
연관 서버 API: GET /post/question/filter/
@Esdyee

**Comment by Esdyee** [comment]
네 작업하셔도 좋을 것 같습니다.

**Comment by cmygray** [comment]
/user/<pk>/following-expertise||following-interest/ API로 변경할게요.

`?page_size=3&page=1` 쿼리 응답 데이터를 사용하면 될 것 같습니다.

**Comment by cmygray** [comment]
완료
